### ISSUE TITLE
Nina.msi version 2.0 missing in the repository

### ISSUE THREAD

**Issue by outis79** [franpossetto/Nina#35]
Hi,
I can't find the installer Nina.msi for the 2.0 version in the repository. The link in the main page for downloading it leads to "not found" page. 
There is a Nina.exe file which installs the 1.4.3 version 
Thank you.

**Comment by franpossetto** [comment]
Hi Outis, sorry for the delay in responding this message. 
You can find the latest version in www.ninabim.com. There are incompabilities between the version 1.4.3 and the 2.0.0. If you still have the issue I'll be happy to help you to uninstall the older version and install the new one. 

Just let me know.
Kind regards and thanks for reporting the issue.
