### ISSUE TITLE
Nina 4.7.3 - Open views not working

### ISSUE THREAD

**Issue by outis79** [franpossetto/Nina#36]
Hi,
I get the error attached with Open Views
![ninaerror](https://user-images.githubusercontent.com/128253971/226133533-4be9d5e6-b850-4f05-a2af-dc0ac58ef268.PNG)
 Thank you.

**Comment by franpossetto** [comment]
Hey Outis, the command is working again, to install the tool again, first unistall the one you have using "Add or Remove programs" from windows. It should delete the folder Nina.bundle located in C:\ProgramData\Autodesk\ApplicationPlugins.

Then, you can run the installer again. You can find the latest version here.
https://www.ninabim.com/

Have a great day.
