### ISSUE TITLE
External Tools - Invalid Format AddInId message

### ISSUE THREAD

**Issue by Robbo1234** [franpossetto/Nina#39]
**Describe the bug**
Installed Nina for Revit and I am getting this 'External Tools - Invalid Format AddInId' message.

![image](https://github.com/franpossetto/Nina/assets/8776947/7d50490d-072f-4483-a510-9221997b046d)

**Revit Version:**
Revit 2021.1.9

Thanking you in advance
Rob

**Comment by Robbo1234** [comment]
Fyi, Nina for Revit installed in Revit 2022.1 but I got this error when I tried to execute 'Open Multiple Views'

![image](https://github.com/franpossetto/Nina/assets/8776947/41d0f869-00ef-4c19-a57e-9d5be6f41421)

**Comment by franpossetto** [comment]
Hey Rob, thanks for reporting these issues, we are going to work on this today and let you know when is fixed.
Have a great day.

**Comment by Robbo1234** [comment]
Thanks, Francisco

**Comment by franpossetto** [comment]
hey Rob,

The isssue has been fixed. To install the solution again, first unistall the one you have using "Add or Remove programs" from windows. It should delete the folder **Nina.bundle** located in C:\ProgramData\Autodesk\ApplicationPlugins.

Then, you can run the installer again. You can find the latest version here. 
https://www.ninabim.com/

Please let me know if you have any questions or if you find another error.
Thanks again for reporting the issue.

Have a great day !

**Comment by Robbo1234** [comment]
Thanks, Francisco,

Your 'Open multiple views' tool would be a great addition to the PyRevit
suite of tools. Can this be added to PyRevit?

Rob

**Comment by franpossetto** [comment]
Hey Rob, yes, the command can be added to pyRevit, but must be written in python.

**Comment by Robbo1234** [comment]
Thanks, Francisco
